version: '2'

volumes:
  elasticsearch_6_data:
    driver: local

services:
  q_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: q_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - elasticsearch_6_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  test:
    depends_on:
     - q_elasticsearch
    build: .
    ports:
     - '8100:8100'
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - GLOBAL_EVENT_BUS_BASE=https://bus.eventdata.crossref.org
     - QUERY_DEPLOYMENT=test_
     - GLOBAL_ARTIFACT_URL_BASE=https://artifact.eventdata.crossref.org
     - QUERY_EVENT_BUS_BASE=https://bus.eventdata.crossref.org
     - QUERY_PORT=8100
     - QUERY_JWT=TEST
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - QUERY_WHITELIST_OVERRIDE=true
     - QUERY_TERMS_URL=https://doi.org/10.13003/CED-terms-of-use
     - QUERY_PREFIX_WHITELIST_ARTIFACT_NAME=crossref-doi-prefix-list
     - QUERY_ELASTIC_URI=http://q_elasticsearch:9200
    command: "lein run server"



