version: '2'

volumes:
  esdata1:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      - transport.host=elasticsearch
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  test:
    depends_on:
     - elasticsearch
    build: .
    ports:
     - '8100:8100'
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - QUERY_EVENT_BUS_BASE=http://138.201.202.133:8002
     - GLOBAL_ARTIFACT_URL_BASE=http://event-data-artifact-prod.s3.amazonaws.com
     - QUERY_PORT=8100
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - QUERY_WHITELIST_OVERRIDE=true
     - QUERY_TERMS_URL=https://doi.org/10.13003/CED-terms-of-use
    command: "lein run server"

